# -*- coding: utf-8 -*-
"""Copy of son_asama.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TABwKPf6dorKHHNFML8SVoaHpZkGqvM8

# loading and importing libraries to be used in the code
"""

pip install pandas numpy matplotlib  catboost tensorflow seaborn shap tensorflow scikit-learn torch torchvision numpy pillow

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.neural_network import MLPClassifier
import shap
import time
from sklearn.metrics import accuracy_score
import seaborn as sns
from sklearn.ensemble import StackingClassifier
from sklearn.utils.class_weight import compute_class_weight
import tensorflow as tf
from google.colab import drive

"""# load master data and  randomly divide data into two parts"""

drive.mount('/content/drive')
output_file = '/content/drive/MyDrive/Y_LRS_OBAFGKM_A+0.csv'
df = pd.read_csv(output_file,delimiter=",")
df=pd.DataFrame(df)


ddf.columns = ddf.columns.astype(str).str.replace(r'\[', '', regex=True).str.replace(r'\]', '', regex=True)

df = ddf.dropna(subset=['class'], how='any')  # Drop rows where 'class' is NaN=df.dropna(df['class']=="nan")

random_50_percent = new_df.sample(frac=0.5, random_state=42)

remaining_50_percent = new_df.drop(random_50_percent.index)

"""# data preprocessing"""

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt

# ---------------------------------------------------------------
# 1. Veri Ön İşleme
# ---------------------------------------------------------------

# Örnek bir fonksiyon: "O" sınıfını 'o_subclass_target' ile güncelliyor.
def modify_o_class_subclass(df, class_column, subclass_column, o_subclass_target=181):
    modified_df = df.copy()
    modified_df.loc[modified_df[class_column] == 'O', subclass_column] = o_subclass_target
    return modified_df

# final_df değişkeninizin tanımlı ve yüklü olduğunu varsayıyoruz.
class_column = 'class'
subclass_column = 'subclass_value'
o_subclass_target = 181

# Veriyi güncelleme
new_df = modify_o_class_subclass(random_50_percent, class_column, subclass_column, o_subclass_target)

# Özellik (X) ve hedef (y) sütunlarını belirleme
X = new_df.drop(columns=["class", "subclass", "type", "subclass_value"])
y = new_df['class']

# Kayıp değerleri temizleme
X = X.dropna()
y = y.loc[X.index]

# Sadece sayısal özellikleri seçiyoruz
X = X.select_dtypes(include=['number'])

# Ölçeklendirme (Scaling) ve etiket kodlama (Encoding)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

le = LabelEncoder()
y_encoded = le.fit_transform(y)

# Eğitme ve test seti ayırma
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y_encoded, test_size=0.2, random_state=42
)

# LDA ile boyut indirgeme
lda = LDA(n_components=min(len(np.unique(y_encoded)) - 1, X_train.shape[1]))
X_train_lda = lda.fit_transform(X_train, y_train)
X_test_lda = lda.transform(X_test)

"""# model education process"""

# PyTorch tensörlerine dönüştürme
X_train_tensor = torch.tensor(X_train_lda, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.long)
X_test_tensor = torch.tensor(X_test_lda, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.long)

train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
train_loader = DataLoader(train_dataset, batch_size=1024, shuffle=True)

test_dataset = TensorDataset(X_test_tensor, y_test_tensor)
test_loader = DataLoader(test_dataset, batch_size=1024, shuffle=False)

# ---------------------------------------------------------------
# 2. Class Weights Hesaplama
# ---------------------------------------------------------------

# Her sınıfın veri setindeki sayısını al
class_sample_count = np.bincount(y_train)  # Her sınıfın örnek sayısını al
class_weights = 1. / class_sample_count  # Tersine ağırlık (az olan sınıflara daha fazla ağırlık)

# PyTorch tensörüne dönüştür
class_weights_tensor = torch.tensor(class_weights, dtype=torch.float32)

# ---------------------------------------------------------------
# 3. Derin Öğrenme Modeli Tanımı
# ---------------------------------------------------------------

class StarDeepNN(nn.Module):
    def __init__(self, input_dim, num_classes):
        super(StarDeepNN, self).__init__()
        self.fc1 = nn.Linear(input_dim, 256)
        self.bn1 = nn.BatchNorm1d(256)
        self.dropout1 = nn.Dropout(0.4)

        self.fc2 = nn.Linear(256, 128)
        self.bn2 = nn.BatchNorm1d(128)


        self.fc3 = nn.Linear(128, 64)
        self.bn3 = nn.BatchNorm1d(64)


        self.fc4 = nn.Linear(64, num_classes)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.relu(self.bn1(self.fc1(x)))
        x = self.dropout1(x)
        x = self.relu(self.bn2(self.fc2(x)))

        x = self.relu(self.bn3(self.fc3(x)))

        x = self.fc4(x)
        return x

# ---------------------------------------------------------------
# 4. Model, Loss ve Optimizer Tanımı
# ---------------------------------------------------------------

input_dim = X_train_lda.shape[1]
num_classes = len(np.unique(y_encoded))

model = StarDeepNN(input_dim, num_classes)

# Class weights ile CrossEntropyLoss kullanımı
criterion = nn.CrossEntropyLoss(weight=class_weights_tensor)

# Adam optimizer
optimizer = optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-5)

# ---------------------------------------------------------------
# 5. Model Eğitimi
# ---------------------------------------------------------------

def train_with_class_weights(model, loader, criterion, optimizer, epochs=12):
    model.train()
    for epoch in range(epochs):
        total_loss = 0
        for features, labels in loader:
            optimizer.zero_grad()  # Gradients sıfırla
            outputs = model(features)  # Model tahminleri
            loss = criterion(outputs, labels)  # Loss hesapla
            loss.backward()  # Gradients hesapla
            optimizer.step()  # Modeli güncelle
            total_loss += loss.item()
        print(f"Epoch [{epoch + 1}/{epochs}], Loss: {total_loss / len(loader):.4f}")

# Modeli eğitelim
print("Training Model with Class Weights...")
train_with_class_weights(model, train_loader, criterion, optimizer)

# ---------------------------------------------------------------
# 6. Model Test Aşaması
# ---------------------------------------------------------------

def evaluate_model(model, loader):
    model.eval()
    all_preds = []
    all_labels = []
    with torch.no_grad():
        for features, labels in loader:
            outputs = model(features)
            _, predicted = torch.max(outputs, 1)
            all_preds.extend(predicted.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
    return np.array(all_preds), np.array(all_labels)

# Test setinde değerlendirme
y_pred, y_true = evaluate_model(model, test_loader)

# ---------------------------------------------------------------
# 7. Değerlendirme (Confusion Matrix, Classification Report)
# ---------------------------------------------------------------

# Sınıf adlarını label encoder'dan geri alalım
class_names = le.inverse_transform(range(num_classes))

# Confusion Matrix
def plot_confusion_matrix(y_true, y_pred, class_names):
    conf_matrix = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(10, 8))
    sns.heatmap(conf_matrix, annot=True, cmap="Blues", fmt="d",
                xticklabels=class_names, yticklabels=class_names)
    plt.title("Confusion Matrix")
    plt.xlabel("Predicted Class")
    plt.ylabel("True Class")
    plt.show()

plot_confusion_matrix(y_true, y_pred, class_names)

# Classification Report ve Accuracy
print("\nClassification Report:")
print(classification_report(y_true, y_pred, target_names=class_names))

accuracy = accuracy_score(y_true, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

"""# shap(bunu sanırım yiğit koycak)

---


"""

print("\nComputing SHAP values for LDA components...")
import torch.nn.functional as F #
num_samples = 150       # SHAP analizinde kaç test örneği
background_size = 50   # Arkaplan seti boyutu

# LDA uzayı verileri
X_test_lda_sample = X_test_lda[:num_samples]
background = X_train_lda[np.random.choice(X_train_lda.shape[0], background_size, replace=False)]

# LDA katsayıları
lda_coefficients = lda.scalings_

# PyTorch modeli için tahmin wrapper
def predict_wrapper_pytorch(data_numpy):
    """
    data_numpy: (num_samples, n_components) LDA uzayındaki NumPy array.
    Döndürdüğü: (num_samples, n_classes) olasılık tahminleri (Softmax).
    """
    data_torch = torch.tensor(data_numpy, dtype=torch.float32)
    model.eval()
    with torch.no_grad():
        logits = model(data_torch)
        probs = F.softmax(logits, dim=1)
    return probs.cpu().numpy()

# KernelExplainer
explainer = shap.KernelExplainer(predict_wrapper_pytorch, background)
shap_values = explainer.shap_values(X_test_lda_sample)
# shap_values genelde (n_classes, n_samples, n_components) veya (n_samples, n_classes, n_components) olabilir

# Boyutları ayarlayarak orijinal feature uzayına dönüştürme
if len(np.array(shap_values).shape) == 3:
    shap_arr = np.array(shap_values)
    # SHAP sürümünüze göre shape (n_classes, n_samples, n_components) olabilir.
    # n_samples, n_classes, n_components'e dönüştürelim:
    if shap_arr.shape[0] == num_samples:
        # (n_samples, n_classes, n_components)
        n_samples2, n_classes2, n_components2 = shap_arr.shape
    else:
        # (n_classes, n_samples, n_components) -> transpose
        n_classes2, n_samples2, n_components2 = shap_arr.shape
        shap_arr = shap_arr.transpose((1, 0, 2))  # (n_samples, n_classes, n_components)

    shap_values_sum = np.zeros((n_samples2, lda_coefficients.shape[0]))

    for class_idx in range(n_classes2):
        shap_values_class = shap_arr[:, class_idx, :]

        # LDA ve SHAP bileşen sayısı
        if shap_values_class.shape[1] > lda_coefficients.T.shape[0]:
            shap_values_class = shap_values_class[:, :lda_coefficients.T.shape[0]]
        elif shap_values_class.shape[1] < lda_coefficients.T.shape[0]:
            padding = lda_coefficients.T.shape[0] - shap_values_class.shape[1]
            shap_values_class = np.pad(
                shap_values_class, ((0, 0), (0, padding)), 'constant'
            )

        # Orijinal feature uzayına geri dönüş
        shap_vals_orig = np.dot(shap_values_class, lda_coefficients.T)
        # Farklı sınıfların katkılarını mutlaklayarak topluyoruz
        shap_values_sum += np.abs(shap_vals_orig)

    shap_values_mean = shap_values_sum / n_classes2
else:
    shap_values_mean = None
    print("Unexpected shape of shap_values.")

# ---------------------------------------------------------
# 8. SHAP Summary Plot (Orijinal Feature Uzayı)
# ---------------------------------------------------------
i
X_test_scaled = X_test  
feature_names = X.columns  

print("\nSHAP Summary Plot for Original Features")
if shap_values_mean is not None:
    # num_samples kadar satır seçelim (shap_values_mean ile aynı sayıda)
    shap.summary_plot(
        shap_values_mean,
        X_test_scaled[:num_samples],
        feature_names=feature_names
    )
else:
    print("shap_values_mean is None, cannot plot.")

"""# create file in drive"""

import os
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Create the directory if it doesn't exist
folder_path = '/content/drive/MyDrive/son'
os.makedirs(folder_path, exist_ok=True)

print(f"Folder '{folder_path}' created (or already exists).")

"""# register model"""

import joblib
import torch
model_save_path = '/content/drive/MyDrive/son/Son_model_save'
scaler_save_path = "/content/drive/MyDrive/son/scaler.pkl"
lda_save_path = "/content/drive/MyDrive/son/lda.pkl"
label_encoder_save_path = "/content/drive/MyDrive/son/label_encoder.pkl"
# Modeli kayıt et
torch.save(model.state_dict(), model_save_path)

# Scaler, LabelEncoder ve LDA'yı kayıt et
joblib.dump(scaler, scaler_save_path)
joblib.dump(le, label_encoder_save_path)
joblib.dump(lda, lda_save_path)

print("Model, Scaler, LabelEncoder ve LDA kayıt edildi.")

"""# load model"""

# Modeli yeniden yükle
loaded_model = StarDeepNN(input_dim=input_dim, num_classes=num_classes)
loaded_model.load_state_dict(torch.load(model_save_path))
loaded_model.eval()

# Scaler, LabelEncoder ve LDA'yı yükle
scaler_loaded = joblib.load(scaler_save_path)
le_loaded = joblib.load(label_encoder_save_path)
lda_loaded = joblib.load(lda_save_path)

print("Model, Scaler, LabelEncoder ve LDA başarıyla yüklendi.")

"""# train with new data and project the result"""

# Yeni veri setini yükleme ve işleme
  # Yeni veri setinizi buradan yükleyin
def modify_o_class_subclass(df, class_column, subclass_column, o_subclass_target=181):
    modified_df = df.copy()
    modified_df.loc[modified_df[class_column] == 'O', subclass_column] = o_subclass_target
    return modified_df


class_column = 'class'
subclass_column = 'subclass_value'
o_subclass_target = 181

# Modify dataset
new_df = modify_o_class_subclass(remaining_50_percent, class_column, subclass_column, o_subclass_target)
df_new = new_df
new_X = df_new.drop(columns=["class", "subclass", "type", "subclass_value"])

new_X = new_X.dropna()  # Eksik değerleri
df_new = df_new.dropna(subset=['class'])

new_X = new_X.select_dtypes(include=["number"])  # Sadece sayısal kolonları seçin

# Scaler ve LDA ile işleme
new_X_scaled = scaler_loaded.transform(new_X)
new_X_lda = lda_loaded.transform(new_X_scaled)

# Tensöre dönüştürme
new_X_tensor = torch.tensor(new_X_lda, dtype=torch.float32)

# Tahmin yapma
loaded_model.eval()
with torch.no_grad():
    outputs = loaded_model(new_X_tensor)
    _, predictions = torch.max(outputs, 1)

# Tahmin edilen sınıflar
predicted_classes = le_loaded.inverse_transform(predictions.numpy())
print("Tahmin edilen sınıflar:", predicted_classes)
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns

# Tahmin edilen sınıflar
predicted_classes = le_loaded.inverse_transform(predictions.numpy())
true_classes = df_new.loc[new_X.index, 'class'].values
# True classes and predicted classes lengths check
print(f"True classes length: {len(true_classes)}")
print(f"Predicted classes length: {len(predicted_classes)}")



# Check if lengths match
print(f"Adjusted true classes length: {len(true_classes)}")
print(f"Predicted classes length: {len(predicted_classes)}")

# Confusion Matrix
conf_matrix = confusion_matrix(true_classes, predicted_classes, labels=le_loaded.classes_)
plt.figure(figsize=(10, 8))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=le_loaded.classes_, yticklabels=le_loaded.classes_)
plt.title("Confusion Matrix")
plt.xlabel("Predicted Classes")
plt.ylabel("True Classes")
plt.show()

# Model Performans Metrikleri
accuracy = accuracy_score(true_classes, predicted_classes)
print(f"Accuracy: {accuracy:.4f}")

print("\nClassification Report:")
print(classification_report(true_classes, predicted_classes, target_names=le_loaded.classes_))
